# Development override for compose.yml
# Usage: docker compose -f compose.yml -f compose.dev.yml up

services:
  ffprobe-api:
    container_name: ffprobe-api
    build:
      context: .
      dockerfile: Dockerfile
      target: go-builder
    command: go run ./cmd/ffprobe-api
    volumes:
      - .:/app:cached
      - uploads_data:/app/uploads
      - reports_data:/app/reports
      - models_data:/app/models
      - logs_data:/app/logs
      - temp_data:/app/temp
      - cache_data:/app/cache
      - backup_data:/app/backup
      - go_mod_cache:/go/pkg/mod
    environment:
      - LOG_LEVEL=debug
      - ENABLE_AUTH=false
      - ENABLE_RATE_LIMIT=false
      - ENABLE_LOCAL_LLM=true
      - OLLAMA_MODEL=qwen2:1.5b  # Smaller model for development
    restart: "no"
    
  # Add development tools
  adminer:
    image: adminer:4.8.1
    container_name: ffprobe-adminer
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    restart: unless-stopped
    networks:
      - ffprobe-network
      
  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:0.8.1
    container_name: ffprobe-redis-commander
    ports:
      - "8091:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    restart: unless-stopped
    networks:
      - ffprobe-network
      
  # Ollama development settings
  ollama:
    container_name: ffprobe-ollama-dev
    environment:
      - OLLAMA_MODEL=qwen2:1.5b  # Smaller model for development
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=2
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'

volumes:
  go_mod_cache:
    driver: local