# Simple Docker Compose for Small Organizations / Test Deployments
# Lightweight setup without monitoring stack - ready to deploy
# Usage: docker compose -f compose.simple.yml up -d

services:
  # Main API service
  ffprobe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffprobe-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ffprobe_api
      - POSTGRES_USER=ffprobe
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password_change_this}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-dev_redis_pass}
      - LOG_LEVEL=info
      - API_KEY=${API_KEY:-dev_api_key_change_this_minimum_32_chars}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret_change_this_minimum_32_chars}
      - FFMPEG_PATH=/usr/local/bin/ffmpeg
      - FFPROBE_PATH=/usr/local/bin/ffprobe
      - VMAF_MODEL_PATH=/usr/local/share/vmaf
      - UPLOAD_DIR=/app/uploads
      - REPORTS_DIR=/app/reports
      - MAX_FILE_SIZE=53687091200
      - ENABLE_AUTH=true
      - ENABLE_RATE_LIMIT=true
      - RATE_LIMIT_PER_MINUTE=60
      - RATE_LIMIT_PER_HOUR=1000
      - RATE_LIMIT_PER_DAY=10000
      - ENABLE_LOCAL_LLM=${ENABLE_LOCAL_LLM:-true}   # Enabled by default - APIs are LLM-powered
      - OLLAMA_URL=${OLLAMA_URL:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-phi3:mini}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
      ollama:
        condition: service_healthy
        required: false
    volumes:
      - uploads_data:/app/uploads
      - reports_data:/app/reports
      - logs_data:/app/logs
      - temp_data:/app/temp
      - cache_data:/app/cache
    restart: unless-stopped
    networks:
      - ffprobe-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:size=1G,mode=1777
    user: "1001:1001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database
  postgres:
    image: postgres:16.1-alpine
    container_name: ffprobe-postgres
    environment:
      - POSTGRES_DB=ffprobe_api
      - POSTGRES_USER=ffprobe
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password_change_this}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
      - ./migrations/001_initial_schema.up.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./migrations/005_create_quality_metrics_tables.up.sql:/docker-entrypoint-initdb.d/02-quality.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ffprobe -d ffprobe_api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - ffprobe-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    user: "999:999"

  # Redis cache
  redis:
    image: redis:7.2.4-alpine
    container_name: ffprobe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-dev_redis_pass}
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-dev_redis_pass}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - ffprobe-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    user: "999:999"

  # Ollama (Local LLM Service) - Essential for LLM-powered APIs
  ollama:
    image: ollama/ollama:latest
    container_name: ffprobe-ollama-simple
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=${OLLAMA_MODELS_PATH:-/root/.ollama/models}
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_QUEUE=64
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama-entrypoint.sh:/ollama-entrypoint.sh:ro
    restart: unless-stopped
    networks:
      - ffprobe-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    entrypoint: ["/ollama-entrypoint.sh"]

# Simple volumes for data persistence
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local
  reports_data:
    driver: local
  logs_data:
    driver: local
  temp_data:
    driver: local
  cache_data:
    driver: local
  ollama_data:
    driver: local

# Simple network
networks:
  ffprobe-network:
    driver: bridge