# Development override for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  ffprobe-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: go-builder
    command: go run ./cmd/ffprobe-api
    volumes:
      - .:/app:cached
      - uploads_data:/app/uploads
      - reports_data:/app/reports
      - models_data:/app/models
      - logs_data:/app/logs
      - temp_data:/app/temp
      - cache_data:/app/cache
      - backup_data:/app/backup
      - go_mod_cache:/go/pkg/mod
    environment:
      - LOG_LEVEL=debug
      - ENABLE_AUTH=false
      - ENABLE_RATE_LIMIT=false
    restart: "no"
    
  # Add development tools
  adminer:
    image: adminer:latest
    container_name: ffprobe-adminer
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    restart: unless-stopped
    networks:
      - ffprobe-network
      
  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ffprobe-redis-commander
    ports:
      - "8091:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    restart: unless-stopped
    networks:
      - ffprobe-network

volumes:
  go_mod_cache:
    driver: local