# Prometheus configuration for Grafana Cloud integration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ffprobe-api'
    environment: '${GO_ENV:-development}'

# Remote write to Grafana Cloud
remote_write:
  - url: '${GRAFANA_CLOUD_URL}/api/prom/push'
    basic_auth:
      username: '${GRAFANA_CLOUD_USERNAME}'
      password: '${GRAFANA_CLOUD_API_KEY}'
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*|process_.*|promhttp_.*'
        action: drop

rule_files:
  - "rules/*.yml"

scrape_configs:
  # FFprobe API metrics
  - job_name: 'ffprobe-api'
    static_configs:
      - targets: ['ffprobe-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Ollama/AI service metrics
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node/system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 60s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 60s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093